# Generated by Django 3.2.16 on 2023-05-27 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.TextField(verbose_name='Article Preview Image Link')),
                ('img', models.TextField(blank=True, verbose_name='Article Image Link')),
                ('title', models.TextField(verbose_name='Article Title')),
                ('text', models.TextField(verbose_name='Article Text')),
                ('youtube_link', models.TextField(blank=True, verbose_name='Article Youtube Video Link')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Comment Author')),
                ('text', models.TextField(verbose_name='Comment Text')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
    ]
